name: "check-version"
description: "Checks, if the current project-version in the pyproject.toml is already existing as a tag. Fails, if that tag already exists"

inputs:
  token:
    description: "Github token to make authed request to GH API"
    required: true
  poetry-version:
    description: "Version of poetry to install"
    required: false
    default: "1.1.14"
  python-version:
    description: "Version of python to install"
    required: false
    default: "3.10"

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup poetry
      id: setup-poetry
      uses: henningwoehr/action-poetry-setup@v1
      with:
        python-version: ${{ inputs.python-version }}
        poetry-version: ${{ inputs.poetry-version }}

    - name: validate version
      run: |
        RELEASE_OLD=$(curl -sL https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest --header "Authorization: Bearer ${{ inputs.token }}" | jq -r ".tag_name")
        if [[ $RELEASE_OLD -eq null ]]
        then
          RELEASE_OLD=$(echo "0.0.0")
        fi
        POETRY_NEW=$(poetry version --short)
        python -c """
        import sys
        from packaging import version
        if version.parse(sys.argv[1]) >= version.parse(sys.argv[2]):
            raise ValueError('Poetry Version is not larger than the last release')
        """ $RELEASE_OLD $POETRY_NEW
      shell: bash